Readme func and python ecosystem
UBC-MDS/autopredictor pull request #7
Opened 2024-01-11 06:01 UTC by s-voon

Hi Anu, I revised the README.md function to include the functions list and where our package fit within the phyton ecosystem, please review them. 
Note: function names are tentative and subjects to change based on the src python scripts

2024-01-11 21:10 UTC, AnuBanga requested changes
Please find suggestions.

2024-01-11 21:10 UTC, AnuBanga commented on README.md
> +- `fit`: Fits a clean, preprocessed training data into eight different regression models. The fuinction returns a dictonary containing four various metric scores for each model
There are minor spelling errors
```suggestion
- `fit`: Fits a clean, preprocessed training data into eight different regression models. The function returns a dictionary containing four various metric scores for each model
```

2024-01-11 21:31 UTC, s-voon commented
Thanks for reviewing! Fixed the typos :)

2024-01-12 03:44 UTC, AnuBanga approved these changes
Reviewed

2024-01-12 03:44 UTC, merged